export const REQUEST_TEMPS_PENDING = 'REQUEST_TEMPS_PENDING';
export const REQUEST_TEMPS_SUCESS = 'REQUEST_TEMPS_SUCESS';
export const REQUEST_TEMPS_FAILED = 'REQUEST_TEMPS_FAILED';
export const MIN_TEMP = 'MIN_TEMP';
export const MAX_TEMP = 'MAX_TEMP';